# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/oleksandr/CLIon/clion-2016.3.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/oleksandr/CLIon/clion-2016.3.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oleksandr/newShell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oleksandr/newShell/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/oleksandr/CLIon/clion-2016.3.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/oleksandr/CLIon/clion-2016.3.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleksandr/newShell/cmake-build-debug/CMakeFiles /home/oleksandr/newShell/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleksandr/newShell/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mkdir

# Build rule for target.
mkdir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkdir
.PHONY : mkdir

# fast build rule for target.
mkdir/fast:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/build
.PHONY : mkdir/fast

#=============================================================================
# Target rules for targets named ls

# Build rule for target.
ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls
.PHONY : ls

# fast build rule for target.
ls/fast:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/build
.PHONY : ls/fast

#=============================================================================
# Target rules for targets named mv

# Build rule for target.
mv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mv
.PHONY : mv

# fast build rule for target.
mv/fast:
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/build
.PHONY : mv/fast

#=============================================================================
# Target rules for targets named cp

# Build rule for target.
cp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cp
.PHONY : cp

# fast build rule for target.
cp/fast:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/build
.PHONY : cp/fast

#=============================================================================
# Target rules for targets named rm

# Build rule for target.
rm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm
.PHONY : rm

# fast build rule for target.
rm/fast:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/build
.PHONY : rm/fast

#=============================================================================
# Target rules for targets named newShell

# Build rule for target.
newShell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 newShell
.PHONY : newShell

# fast build rule for target.
newShell/fast:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/build
.PHONY : newShell/fast

builtin.o: builtin.cpp.o

.PHONY : builtin.o

# target to build an object file
builtin.cpp.o:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/builtin.cpp.o
.PHONY : builtin.cpp.o

builtin.i: builtin.cpp.i

.PHONY : builtin.i

# target to preprocess a source file
builtin.cpp.i:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/builtin.cpp.i
.PHONY : builtin.cpp.i

builtin.s: builtin.cpp.s

.PHONY : builtin.s

# target to generate assembly for a file
builtin.cpp.s:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/builtin.cpp.s
.PHONY : builtin.cpp.s

cp.o: cp.cpp.o

.PHONY : cp.o

# target to build an object file
cp.cpp.o:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/cp.cpp.o
.PHONY : cp.cpp.o

cp.i: cp.cpp.i

.PHONY : cp.i

# target to preprocess a source file
cp.cpp.i:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/cp.cpp.i
.PHONY : cp.cpp.i

cp.s: cp.cpp.s

.PHONY : cp.s

# target to generate assembly for a file
cp.cpp.s:
	$(MAKE) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/cp.cpp.s
.PHONY : cp.cpp.s

filescript.o: filescript.cpp.o

.PHONY : filescript.o

# target to build an object file
filescript.cpp.o:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/filescript.cpp.o
.PHONY : filescript.cpp.o

filescript.i: filescript.cpp.i

.PHONY : filescript.i

# target to preprocess a source file
filescript.cpp.i:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/filescript.cpp.i
.PHONY : filescript.cpp.i

filescript.s: filescript.cpp.s

.PHONY : filescript.s

# target to generate assembly for a file
filescript.cpp.s:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/filescript.cpp.s
.PHONY : filescript.cpp.s

help.o: help.cpp.o

.PHONY : help.o

# target to build an object file
help.cpp.o:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/help.cpp.o
.PHONY : help.cpp.o

help.i: help.cpp.i

.PHONY : help.i

# target to preprocess a source file
help.cpp.i:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/help.cpp.i
.PHONY : help.cpp.i

help.s: help.cpp.s

.PHONY : help.s

# target to generate assembly for a file
help.cpp.s:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/help.cpp.s
.PHONY : help.cpp.s

ls.o: ls.cpp.o

.PHONY : ls.o

# target to build an object file
ls.cpp.o:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/ls.cpp.o
.PHONY : ls.cpp.o

ls.i: ls.cpp.i

.PHONY : ls.i

# target to preprocess a source file
ls.cpp.i:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/ls.cpp.i
.PHONY : ls.cpp.i

ls.s: ls.cpp.s

.PHONY : ls.s

# target to generate assembly for a file
ls.cpp.s:
	$(MAKE) -f CMakeFiles/ls.dir/build.make CMakeFiles/ls.dir/ls.cpp.s
.PHONY : ls.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/main.cpp.s
.PHONY : main.cpp.s

mkdir.o: mkdir.cpp.o

.PHONY : mkdir.o

# target to build an object file
mkdir.cpp.o:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/mkdir.cpp.o
.PHONY : mkdir.cpp.o

mkdir.i: mkdir.cpp.i

.PHONY : mkdir.i

# target to preprocess a source file
mkdir.cpp.i:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/mkdir.cpp.i
.PHONY : mkdir.cpp.i

mkdir.s: mkdir.cpp.s

.PHONY : mkdir.s

# target to generate assembly for a file
mkdir.cpp.s:
	$(MAKE) -f CMakeFiles/mkdir.dir/build.make CMakeFiles/mkdir.dir/mkdir.cpp.s
.PHONY : mkdir.cpp.s

mv.o: mv.cpp.o

.PHONY : mv.o

# target to build an object file
mv.cpp.o:
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/mv.cpp.o
.PHONY : mv.cpp.o

mv.i: mv.cpp.i

.PHONY : mv.i

# target to preprocess a source file
mv.cpp.i:
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/mv.cpp.i
.PHONY : mv.cpp.i

mv.s: mv.cpp.s

.PHONY : mv.s

# target to generate assembly for a file
mv.cpp.s:
	$(MAKE) -f CMakeFiles/mv.dir/build.make CMakeFiles/mv.dir/mv.cpp.s
.PHONY : mv.cpp.s

proccess.o: proccess.cpp.o

.PHONY : proccess.o

# target to build an object file
proccess.cpp.o:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/proccess.cpp.o
.PHONY : proccess.cpp.o

proccess.i: proccess.cpp.i

.PHONY : proccess.i

# target to preprocess a source file
proccess.cpp.i:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/proccess.cpp.i
.PHONY : proccess.cpp.i

proccess.s: proccess.cpp.s

.PHONY : proccess.s

# target to generate assembly for a file
proccess.cpp.s:
	$(MAKE) -f CMakeFiles/newShell.dir/build.make CMakeFiles/newShell.dir/proccess.cpp.s
.PHONY : proccess.cpp.s

rm.o: rm.cpp.o

.PHONY : rm.o

# target to build an object file
rm.cpp.o:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/rm.cpp.o
.PHONY : rm.cpp.o

rm.i: rm.cpp.i

.PHONY : rm.i

# target to preprocess a source file
rm.cpp.i:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/rm.cpp.i
.PHONY : rm.cpp.i

rm.s: rm.cpp.s

.PHONY : rm.s

# target to generate assembly for a file
rm.cpp.s:
	$(MAKE) -f CMakeFiles/rm.dir/build.make CMakeFiles/rm.dir/rm.cpp.s
.PHONY : rm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mkdir"
	@echo "... ls"
	@echo "... mv"
	@echo "... cp"
	@echo "... edit_cache"
	@echo "... rm"
	@echo "... newShell"
	@echo "... builtin.o"
	@echo "... builtin.i"
	@echo "... builtin.s"
	@echo "... cp.o"
	@echo "... cp.i"
	@echo "... cp.s"
	@echo "... filescript.o"
	@echo "... filescript.i"
	@echo "... filescript.s"
	@echo "... help.o"
	@echo "... help.i"
	@echo "... help.s"
	@echo "... ls.o"
	@echo "... ls.i"
	@echo "... ls.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mkdir.o"
	@echo "... mkdir.i"
	@echo "... mkdir.s"
	@echo "... mv.o"
	@echo "... mv.i"
	@echo "... mv.s"
	@echo "... proccess.o"
	@echo "... proccess.i"
	@echo "... proccess.s"
	@echo "... rm.o"
	@echo "... rm.i"
	@echo "... rm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

